name: Build & Test
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test_master:
    name: Build and Test Master ROS ${{ matrix.ros_version }} ${{ matrix.ros_distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [kinetic, melodic]
        include:
        - ros_distro: noetic
          ubuntu_distro: focal
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu_distro }}-ros-${{ matrix.ros_distro }}-ros-base-latest
    env:
      # Needed for the CMakeLists.txt setup
      ROS_DISTRO: ${{ matrix.ros_distro }}
      ROS_VERSION: 1
    steps:
    # Needed to access the vcs repos file from the workspace
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Run action-ros-ci to build and test
      uses: ros-tooling/action-ros-ci@0.1.2
      with:
        target-ros1-distro: ${{ env.ROS_VERSION == '1' && matrix.ros_distro || '' }}
        target-ros2-distro: ${{ env.ROS_VERSION == '2' && matrix.ros_distro || '' }}
        package-name: toposens_task
        vcs-repo-file-url: ''
    - name: Upload resulting colcon logs
      uses: actions/upload-artifact@v2.2.2
      with:
        name: colcon-logs-${{ matrix.ubuntu_distro }}-ros-${{ matrix.ros_distro }}
        path: ros_ws/log
